name: Node.js package 

on: 
  push:
    branches: 
      - main

jobs: 
  publish-gpr:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com/
          scope: '@energma'
      - run: pnpm install
      - run: pnpm publish
        env: 
          NPM_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
